#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.2.16f1_39a4ac3d51f6"
#define UNITY_VERSION_FULL_NICE "2018.2.16f1 (39a4ac3d51f6)"
#define UNITY_VERSION_BLD 3777708
#define UNITY_VERSION_DATE 1541678202
#define UNITY_VERSION_WIN "2018.2.16.3777708"
#define UNITY_VERSION_BRANCH "2018.2/staging"
